4S/4semWork/sweater/src/main/java/com/example/sweater/domain/ChatMessage.java
package com.example.sweater.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonView;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table
@ToString(of = {"id", "text"})
@EqualsAndHashCode(of = {"id"})

public class ChatMessage {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @JsonView(Views.Id.class)
    private Long id;
    @JsonView(Views.IdName.class)
    private String text;

    @Column(updatable = false)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonView(Views.FullMessage.class)
    private LocalDateTime creationDate;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public LocalDateTime getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(LocalDateTime creationDate) {
        this.creationDate = creationDate;
    }
}

4S/4semWork/sweater/src/main/java/com/example/sweater/domain/Classic.java
package com.example.sweater.domain;

public class Classic {
}

4S/4semWork/sweater/src/main/java/com/example/sweater/domain/Message.java
package com.example.sweater.domain;

import com.example.sweater.domain.util.MessageHelper;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

@Entity
public class Message implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotBlank(message = "Please fill the message")
    @Length(max = 2048, message = "Message too large(more than 2kB)")
    private String text;

    @Length(max = 255, message = "Message too large(more than 255)")
    private String tag;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private User author;
//
    private String filename;

    @Column(name="pic")
    private byte[] pic;

    @ManyToMany
    @JoinTable(
            name = "message_likes",
            joinColumns = { @JoinColumn(name = "message_id")},
            inverseJoinColumns = { @JoinColumn(name = "user_id")}
    )
    private Set<User> likes = new HashSet<>();

    public byte[] getPic() {
        return pic;
    }

    public void setPic(byte[] pic) {
        this.pic = pic;
    }

    public Message() {

    }

    public Message(String text, String tag, User author) {
        this.text = text;
        this.tag = tag;
        this.author = author;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }



    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getAuthorName(){
        return MessageHelper.getAuthorName(author);
    }


    public String getText() {
        return text;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public void setText(String text) {
        this.text = text;
    }

    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    public Set<User> getLikes() {
        return likes;
    }

    public void setLikes(Set<User> likes) {
        this.likes = likes;
    }
}

4S/4semWork/sweater/src/main/java/com/example/sweater/domain/Role.java
package com.example.sweater.domain;

import org.springframework.security.core.GrantedAuthority;

public enum Role implements GrantedAuthority {
    USER, ADMIN;

    @Override
    public String getAuthority() {
        return name();
    }
}

4S/4semWork/sweater/src/main/java/com/example/sweater/domain/Views.java
package com.example.sweater.domain;

public final class Views {
    public interface Id {}

    public interface IdName extends Id {}

    public interface FullMessage extends Id {}
}

4S/4semWork/sweater/src/main/java/com/example/sweater/domain/dto/CaptchaResponseDto.java
package com.example.sweater.domain.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Set;

@JsonIgnoreProperties(ignoreUnknown = true)
public class CaptchaResponseDto {
    private boolean success;
    @JsonAlias
    private Set<String> errorCodes;

    public boolean isSuccess() {
        return success;
    }

    public void setSuccess(boolean success) {
        this.success = success;
    }

    public Set<String> getErrorCodes() {
        return errorCodes;
    }

    public void setErrorCodes(Set<String> errorCodes) {
        this.errorCodes = errorCodes;
    }
}

4S/4semWork/sweater/src/main/java/com/example/sweater/domain/dto/EventType.java
package com.example.sweater.domain.dto;

public enum EventType {
    CREATE, UPDATE, REMOVE
}

4S/4semWork/sweater/src/main/java/com/example/sweater/controller/GroupController.java
package com.example.sweater.controller;

public class GroupController {
}

4S/4semWork/sweater/src/main/java/com/example/sweater/controller/MainController.java
package com.example.sweater.controller;

import com.example.sweater.domain.Group;
import com.example.sweater.domain.Message;
import com.example.sweater.domain.User;
import com.example.sweater.domain.dto.MessageDto;
import com.example.sweater.repos.ChatMessageRepo;
import com.example.sweater.repos.GroupRepo;
import com.example.sweater.repos.MessageRepo;
import com.example.sweater.repos.SkillRepo;
import com.example.sweater.service.MessageService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import org.springframework.web.util.UriComponents;
import org.springframework.web.util.UriComponentsBuilder;

import javax.validation.Valid;
import java.io.File;
import java.io.IOException;
import java.util.*;


@Controller
public class MainController {

    @Autowired
    private MessageService messageService;
    @Autowired
    private MessageRepo messageRepo;
    private ChatMessageRepo chatMessageRepo;
    @Autowired
    GroupRepo groupRepo;
    @Autowired
    SkillRepo skillRepo;
    @Autowired
    public MainController(ChatMessageRepo chatMessageRepo) {
        this.chatMessageRepo = chatMessageRepo;
    }


    @Value("${upload.path}")
    private String uploadPath;

    @GetMapping("/chat")
    public String main(Model model, @AuthenticationPrincipal User user) {
        HashMap<Object, Object> data = new HashMap<>();
        if(user!=null) {
            data.put("profile", user);
            data.put("messages", chatMessageRepo.findAll());
        }
        model.addAttribute("frontendData", data);
        System.out.println("hello! Index.");
        return "index";
    }


    @GetMapping("/main/group/{group}")
    public String getgroup(
            @RequestParam(required = false, defaultValue = "") String filter,
            @AuthenticationPrincipal User cur_user,
            Model model,
            @PathVariable long group) {

        Optional<Group> gr = groupRepo.findById(group);
        System.out.println(gr.get().getName() + "//////////////////////////////");
        model.addAttribute("group",groupRepo.findById(group).get());
        System.out.println();
        return "group";
    }


    @GetMapping("/")
    public String greeting(Map<String, Object> model) {
        return "greeting";
    }

    @GetMapping("/main")
    public String main(@RequestParam(required = false, defaultValue = "") String filter, Model model,
                       Pageable pageable,
                       @AuthenticationPrincipal User  user) {
        Page<MessageDto> page =  messageService.messageList(pageable, filter, user);

        System.out.println(page.getTotalElements() + "all elements!!!!!!!!!!!!!!!!!!!!!!1");

        model.addAttribute("page", page);
        model.addAttribute("url", "/main");
        model.addAttribute("filter", filter);
        return "main";
    }

    @GetMapping("/main/{user}")
    public String mainUser_Id(
            @RequestParam(required = false, defaultValue = "") String filter,
            @AuthenticationPrincipal User cur_user,
            Model model,
            @PathVariable User user,
            Pageable pageable) {
        Page<MessageDto> page = null;

        if (filter != null && !filter.isEmpty()) {

//            messages = messageRepo.findByTag(filter);
            page = messageRepo.findByTagAndAuthor(filter, user, pageable);
        } else {

            page = messageRepo.findByAuthor(user, pageable);
        }
//        System.out.println( "////////////////\\\\\\\\\\\\///////////\\\\\\\\/////////Hello! " + page.getContent());
//        System.out.println(page.getContent().get(0).getId() + "////////////////\\\\\\\\\\\\///////////\\\\\\\\/////////Hello! " + page.getContent().get(0).getAuthor());

        model.addAttribute("page", page);
        model.addAttribute("url", "/main");
        model.addAttribute("messages", page);
        model.addAttribute("filter", filter);
        model.addAttribute("userChannel", user);
        model.addAttribute("subscriptionsCount", user.getSubscriptions().size());
        model.addAttribute("subscribersCount", user.getSubscribers().size());
        System.out.println(user.getSubscribers().size());
        model.addAttribute("isSubscriber", user.getSubscribers().contains(cur_user));
        System.out.println( user.getSubscribers().contains(cur_user));
        model.addAttribute("isCurrentUser", cur_user.equals(user));
        model.addAttribute("group",groupRepo.findUsersGroup(user.getId()));
        model.addAttribute("skill",skillRepo.findUsersSkills(user.getId()));
//        System.out.println("i am HEEEEEEEEEEEEEEEEEEEEEEEEREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE33399992s");

        return "main";
    }


    // request param = get info from form or URL param
    @PostMapping("/main/{user}")
    public String add2(
            @PathVariable User user,
    @RequestParam("file") MultipartFile file,
            @AuthenticationPrincipal User cur_user,
            @Valid Message message,
            BindingResult bindingResult,
            Model model
    ) throws IOException {
        System.out.println("i am HEEEEEEEEEEEEEEEEEEEEEEEEREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE3339999");
        return getString(file, cur_user, message, bindingResult, model, user);
    }

    @PostMapping("/main")
    public String add(
            @RequestParam("file") MultipartFile file,
            @AuthenticationPrincipal User cur_user,
            @Valid Message message,
            BindingResult bindingResult,
            Model model
    ) throws IOException {
//        System.out.println("i am HEEEEEEEEEEEEEEEEEEEEEEEEREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE333");
        return getString(file, cur_user, message, bindingResult, model, null);
    }



    @PostMapping("/maindelete")
    public String delete(
            @Valid Message message,
            Model model,
            Pageable pageable,
            @AuthenticationPrincipal User  user
    ) {

        Page<MessageDto> page =  messageService.messageList(pageable, null, user);
        System.out.println(message.getAuthorName() + "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!||| " + message.getText() + " " + message.getId());
        messageRepo.delete(message);
//        message = null;

//        for(Message msg: messages){
//            System.out.println(msg.getAuthor() + " " + msg.getText());
//        }
        model.addAttribute("messages", page);
        model.addAttribute("url", "/main");


        return "redirect:/main";
    }


    @PostMapping("/mainchange")
    public String update(
            @RequestParam("file") MultipartFile file,
            @AuthenticationPrincipal User user,
            @Valid Message message,
            BindingResult bindingResult,
            Model model
    ) throws IOException {


        System.out.println(message.getFilename());
        System.out.println(file.getOriginalFilename() + "HEYs " + message.getId() );
        return getString(file, user, message, bindingResult, model,null);
    }

    private String getString(@RequestParam("file") MultipartFile file, @AuthenticationPrincipal User cur_user, @Valid Message message, BindingResult bindingResult, Model model, User user) throws IOException {
        message.setAuthor(cur_user);


        if (bindingResult.hasErrors()) {
            Map<String, String> errorsMap = ControllerUtils.getErrors(bindingResult);
            model.mergeAttributes(errorsMap);
            model.addAttribute("message", message);
            System.out.println("/////////222");
        } else {


            if (file != null && !file.getOriginalFilename().isEmpty()) {
                File uploadDir = new File(uploadPath);

                if (!uploadDir.exists()) {
                    uploadDir.mkdir();
                }

                String uuidFile = UUID.randomUUID().toString();
                String resultFileName = uuidFile + "." + file.getOriginalFilename();
                System.out.println(uploadPath + "/////////");
                System.out.println(resultFileName + "/////////");

                file.transferTo(new File(uploadPath + "\\" + resultFileName));
                message.setFilename(resultFileName);
            }
            System.out.println( "/////////333");
            model.addAttribute("message", null);
            System.out.println(message.getFilename());
            messageRepo.save(message);

        }
        Iterable<Message> messages = messageRepo.findAll();
        model.addAttribute("messages", messages);
        if(user != null) return "redirect:/main/{user}"; else
         return "redirect:/main";
    }

    @GetMapping("/messages/{message}/like")
    public void like(
            @AuthenticationPrincipal User cur_user,
            @PathVariable Message message,
            RedirectAttributes redirectAttributes,
            @RequestHeader(required = false) String referer
            ) {
        Set<User> likes = message.getLikes();

        if(likes.contains(cur_user)) {
            likes.remove(cur_user);
        }else {
            likes.add(cur_user);
        }


        UriComponents uriComponents = UriComponentsBuilder.fromHttpUrl(referer).build();
        uriComponents.getQueryParams()
                .entrySet()
                .forEach(pair -> redirectAttributes.addAttribute(pair.getKey(), pair.getValue()));
//        return "redirect:" + uriComponents.getPath();
    }


}

4S/4semWork/sweater/src/main/java/com/example/sweater/controller/MessageController.java
package com.example.sweater.controller;

import com.example.sweater.domain.ChatMessage;
import com.example.sweater.domain.Views;
import com.example.sweater.domain.dto.EventType;
import com.example.sweater.domain.dto.ObjectType;
import com.example.sweater.repos.ChatMessageRepo;
import com.example.sweater.repos.MessageRepo;
import com.example.sweater.util.WsSender;
import com.fasterxml.jackson.annotation.JsonView;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.messaging.handler.annotation.MessageMapping;
import org.springframework.messaging.handler.annotation.SendTo;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.function.BiConsumer;

@RestController
@RequestMapping("message")
public class MessageController {
    private final ChatMessageRepo messageRepo;
    private final BiConsumer<EventType, ChatMessage> wsSender;

    @Autowired
    public MessageController(ChatMessageRepo messageRepo, WsSender wsSender) {
        this.messageRepo = messageRepo;
        this.wsSender = wsSender.getSender(ObjectType.MESSAGE, Views.IdName.class);
    }

    @GetMapping
    @JsonView(Views.IdName.class)
    public List<ChatMessage> list() {
        return messageRepo.findAll();
    }

    @GetMapping("{id}")
    @JsonView(Views.FullMessage.class)
    public ChatMessage getOne(@PathVariable("id") ChatMessage chatMessage) {
        return chatMessage;
    }

    @PostMapping
    public ChatMessage create(@RequestBody ChatMessage message) {
        message.setCreationDate(LocalDateTime.now());
        ChatMessage updatedMessage = messageRepo.save(message);
        wsSender.accept(EventType.CREATE, updatedMessage);
        return updatedMessage;
    }

    @PutMapping("{id}")
    public ChatMessage update(
            @PathVariable("id") ChatMessage messageFromDb,
            @RequestBody ChatMessage message
    ) {
        BeanUtils.copyProperties(message, messageFromDb, "id");

        ChatMessage updatedMessage = messageRepo.save(messageFromDb);

        wsSender.accept(EventType.UPDATE, updatedMessage);

        return updatedMessage;
    }

    @DeleteMapping("{id}")
    public void delete(@PathVariable("id") ChatMessage message) {
        messageRepo.delete(message);
        wsSender.accept(EventType.REMOVE, message);
    }
}

4S/4semWork/sweater/src/main/resources/templates/addtogroup.ftl
<#import "parts/common.ftl" as c>

<@c.page>
<h3><b>Group management</b></h3>
<ul class="list-group">
        <li class="list-group-item">
            <h3><b>Add to groups:</b></h3>
          <#list groups as gr>
              <div class="row align-items-left">
              <h4>${gr.name}</h4>
              <form method="post" enctype="multipart/form-data" class="was-validated" action="/user/addtogroup/">
                <input type="text" class="form-control"
                       value="${user.id}" id="user" name="user" placeholder="user" style="display: none" readonly/>
                <input type="text" class="form-control"
                       value="${gr.id}" id="group" name="group" placeholder="group" style="display: none" readonly/>
                <input type="hidden" name="_csrf" value="${_csrf.token}"/>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">add</button>
                </div>
            </form>
              </div>
            </#list>
        </li>

    <li class="list-group-item">
        <h3><b> Remove from groups:</b></h3>
        <#list groupstodelete as gr>
            <div class="row align-items-left">
                <h4>${gr.name}</h4>
                <form method="post" enctype="multipart/form-data" class="was-validated" action="/user/deletefromgroup">
                    <input type="text" class="form-control"
                           value="${user.id}" id="user" name="user" placeholder="user" style="display: none" readonly/>
                    <input type="text" class="form-control"
                           value="${gr.id}" id="group" name="group" placeholder="group" style="display: none" readonly/>
                    <input type="hidden" name="_csrf" value="${_csrf.token}"/>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">remove</button>
                    </div>
                </form>
            </div>
        </#list>
    </li>
</ul>
</@c.page>

4S/4semWork/sweater/src/main/resources/templates/greeting.ftl
<#-- common with full body + some text -->
<#import "parts/common.ftl" as c>

<@c.page>
<h5>Hello, guest</h5>
<div>That is simple page of Max Vseman.</div>
</@c.page>

4S/4semWork/sweater/src/main/resources/templates/group.ftl
<#import "parts/common.ftl" as c>

<@c.page>
<div id="myModal" class="modal">
    <span class="close">&times;</span>
    <img class="modal-content" id="img01"/>
    <div id="caption"></div>
</div>
<div class="container">
    <div class="card">
<h3><b>${group.name}</b></h3>
<div><h4>Tag: #${group.tag}</h4></div>
<div><h4>Lider: ${group.author.username}</h4></div>
<#--<div><h3>${group.text}</h3></div>-->
<#--<div><h3>${group.author}</h3></div>-->
        <img src="/img/${group.filename}" alt="myImg${group.id}" class="card-img-top" id="myImg${group.id}"
             onclick="Modal(this)"/>
<ul class="list-group">
    <#list group.participants as user>
        <li class="list-group-item">
            <a href="/main/${user.id}">${user.getUsername()}</a>
        </li>
    </#list>
</ul>
    </div>
</@c.page>

4S/4semWork/sweater/src/main/resources/templates/groups.ftl
<#macro groups group>

<#--<h3><b>${userChannel.username}'s</b></h3>-->
<div><h3>Groups</h3></div>
<ul class="list-group">
    <#list group as gr>
        <li class="list-group-item">
            <a href="/main/group/${gr.id}">${gr.getName()}</a>
        </li>
    </#list>
</ul>
</#macro>

4S/4semWork/sweater/src/main/resources/templates/main.ftl
<#import "parts/common.ftl" as c>
<#import "subs.ftl" as s>
<#import "groups.ftl" as gr>
<#import "parts/pager.ftl" as p>
<#import "skills.ftl" as sk>


<#-- search->main(Filter), add new post 3 field, with validation  -->
<#assign
user = Session.SPRING_SECURITY_CONTEXT.authentication.principal
name = user.getUsername()
isAdmin = user.isAdmin()
userid = user.getId()
>

<@c.page >

<div id="myModal" class="modal">
    <span class="close">&times;</span>
    <img class="modal-content" id="img01"/>
    <div id="caption"></div>
</div>
 <#if userChannel??>
 <h3>Cabinet of <b>${userChannel.getUsername()}</b></h3>
     <a class="nav-link" href="/user/sendmessage/${userChannel.id}">send message</a>
     <h4>something about me: ${userChannel.aboutme}</h4>

 <#else>
 <h3>All snippets</h3>

 </#if>
    <#if subscriptionsCount??>
        <@s.subs isSubscriber isCurrentUser userChannel subscriptionsCount subscribersCount/>
        <@gr.groups group/>
        <@sk.skill skill/>
    </#if>
<#--<#macro isCurrentUser isSubscriber userChannel subscriptionsCount subscribersCount>-->

<div class="form-row">
    <div class="form-group col-md-6">
        <form method="get" action="/main" class="form-inline">
            <input type="text" name="filter" class="form-control" value="${filter?ifExists}"
                   placeholder="Search by tag">
            <button type="submit" class="btn btn-primary ml-2">Search</button>
        </form>
    </div>
</div>

<a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
   aria-controls="collapseExample">
    Add new snippet
</a>
<div class="collapse <#if message??>show</#if>" id="collapseExample">
    <div class="form-group mt-3">
        <form method="post" enctype="multipart/form-data" class="was-validated">
            <div class="form-group">

                <input type="text" class="form-control ${(textError??)?string('is-invalid', '')}"
                       value="<#if message??>${message.text}</#if>" name="text" placeholder="text"
                       class="form-control is-valid" required/>
                <#if textError??>
                <div class="invalid-feedback">
                    ${textError}
                </div>
                </#if>
            <#--<div class="invalid-feedback">-->
            <#--cannot be empty-->
            <#--</div>-->
            </div>
            <div class="form-group">
                <input type="text" class="form-control" class="form-control is-valid"
                       value="<#if message??>${message.tag}</#if>" name="tag" placeholder="tag"
                       class="form-control is-valid" required/>
                <#if tagError??>
                    <div class="invalid-feedback">
                        ${tagError}
                    </div>
                </#if>

            </div>
            <div class="form-group">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="file" required name="file"/>
                    <label class="custom-file-label" for="validatedCustomFile">file</label>
                </div>
            </div>
            <input type="hidden" name="_csrf" value="${_csrf.token}"/>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Add</button>
            </div>
        </form>
    </div>

</div>

    <@p.pager url page/>
<div class="container">
<#--<@p.pager url page>-->
    <#list page.content as message>
    <#--<a id="like" href="/messages/${message.id}/like">-->
        <#assign
        liked = message.meLiked?string('yes','no')
        imageLikedId ="liked${message.id}"
        imageUnlikedId ="unliked${message.id}"
        likes = "likes${message.id}"
        >
        <div class="card">

        <img src="/img/${message.filename}" alt="myImg${message.id}" class="card-img-top" id="myImg${message.id}"
             onclick="Modal(this)"/>
            <div class="m-2">
                <div class="text${message.id}"><span>${message.text}</span></div>
                <div class="row">
                    <div class="tag${message.id}"><i class="col-sm" >#${message.tag}</i></div>
                <a class="col-sm" href="/main/${message.author.id}">${message.authorName}</a>
                <div class="col-sm" id="likedD${message.id}"
                     onclick="sendLikes(this,'/messages/${message.id}/like', '${liked}','${imageLikedId}','${imageUnlikedId}',${likes})">
                <#--${likes}-->
                <#--${imageLikedId}-->
                <#--${imageUnlikedId}-->
 <#if message.meLiked>
     <i class="fas fa-heart" id="liked${message.id}"></i>
 <#else>
     <i class="far fa-heart" id="unliked${message.id}"></i>
 </#if>
                    <div style="user-select: none;" id="likes${message.id}">${message.likes}</div>
                </div>
                </div>
            </div>

      <#if message.getAuthor().getId()?string == userid?string>
            <div class="btn-group" role="group" aria-label="Basic example">
                <a  type="button" class="btn btn-outline-primary btn-sm" data-toggle="collapse" href="#changeMessage${message.getId()}"
                    aria-controls="collapseExample">
                    change snippet
                </a>

                <form method="post" enctype="multipart/form-data" action="/maindelete">

                    <input type="text" value="${message.id}" name="id" style="display: none" readonly/>

                    <input type="text" class="form-control ${(textError??)?string('is-invalid', '')}"
                           value="<#if message??>${message.text}</#if>" name="text"
                           placeholder="text" style="display: none" readonly/>
                    <input type="text" class="form-control"
                           value="<#if message??>${message.tag}</#if>" name="tag" placeholder="tag" style="display: none" readonly/>
                    <input type="hidden" name="_csrf" value="${_csrf.token}"/>

                    <button type="submit" class="btn btn-danger">delete</button>
                </form>
            </div>
            <div class="card-footer text-muted">

            <#--urlLike = "/messages/${message.id}/like";-->



            <div class="collapse" id="changeMessage${message.getId()}">
                <div class="form-group mt-3">
                    <form method="post" enctype="multipart/form-data" action="/mainchange" class="was-validated">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="file" required name="file"/>
                            <label class="custom-file-label" for="validatedCustomFile">file</label>

                        </div>

                        <div class="form-group">
                            <input type="hidden" value="${message.id}" name="id" style="display: none" readonly/>

                <#if message.filename??>
                            <input type="hidden" value="${message.filename}" name="filename"/>
                </#if>
                            <input type="text" class="form-control ${(textError??)?string('is-invalid', '')}"
                                   value="<#if message??>${message.text}</#if>" name="text"
                                   placeholder="text" class="form-control is-valid" required/>


                <#if textError??>
                <div class="invalid-feedback">
                    ${textError}
                </div>
                </#if>

                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control"
                                   value="<#if message??>${message.tag}</#if>" name="tag" placeholder="tag"
                                   class="form-control is-valid" required/>
                <#if tagError??>
                    <div class="invalid-feedback">
                        ${tagError}
                    </div>
                </#if>
                        </div>
                        <input type="hidden" name="_csrf" value="${_csrf.token}"/>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">change</button>
                        </div>
                    </form>

                </div>

            </div>

            </div>
      </#if>
        </div>
    <#else>
    No message
    </#list>
</div>
    <@p.pager url page/>

</@c.page>

4S/4semWork/sweater/src/main/resources/templates/registration.ftl
<#import "parts/common.ftl" as c>
<#import "parts/login.ftl" as l>

<@c.page >
<div class="mb-1">Add new user</div>
    ${message?ifExists}
    <@l.login "/registration" true />
</@c.page>